# Generated by Django 4.2.10 on 2025-04-02 16:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='code',
            field=models.CharField(choices=[('wedding', 'Bodas'), ('quinceanera', 'Quinceañeras'), ('family', 'Familias'), ('professional', 'Profesional'), ('accessories', 'Accesorios')], default=django.utils.timezone.now, max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='date_added',
            field=models.DateField(auto_now_add=True),
        ),
    ]
